### ISSUE TITLE
Custom settings not working

### ISSUE THREAD

**Issue by arturogalpe** [moodleuulm/moodle-local_boostnavigation#46] opened 2019-08-08 14:23 UTC
Hi,
I just can set the links for title and URL on both custom root and course nodes. And they work fine, but when it comes to adding some other parameters, such as language, supported roles, icon, etc. they don't affect the result. I'm sure I make appropriate use of the '|' separator.
I'm using Moodle 3.7 and Moove theme.

Anyone else with the same issue? Any ideas?

Thank you

**Comment by abias** [comment] 2019-08-27 11:32
Hi @arturogalpe ,

theme_moove is Boost child theme, so this plugin _should_ basically work with it, but it is not guaranteed as Moove's author can also have changed the way the Nav drawer is output in his child theme.

Please try to test your custom node settings with the Boost theme as this is the only theme which we reliably support (see https://github.com/moodleuulm/moodle-local_boostnavigation#theme-support). 

If you can reproduce your problems on Boost, please submit your custom node configuration so that I can replicate your setup.
If you can't reproduce your problems on Boost, please turn to Moove's issue tracker on https://github.com/willianmano/moodle-theme_moove/issues and report your problem there.

Thanks,
Alex

**Comment by abias** [comment] 2020-02-05 06:06
As there hasn't been any more information about the issue anymore, I am going to close this issue now.

Cheers,
Alex

**Closed as completed by abias** 2020-02-05 06:06 UTC
