### ISSUE TITLE
"My courses" Heading Inaccessible

### ISSUE THREAD

**Issue by mepfaff** [moodleuulm/moodle-local_boostnavigation#13] opened 2018-06-28 14:40 UTC
Hello,

Thanks so much for the excellent plugin. My issue: could you please make the "My courses" heading a true link? Right now it can't be accessed using the tab key (for users who can only navigate by keyboard) and it doesn't appear on the list of links provided by a screen reader. 

Thank you!

**Comment by abias** [comment] 2018-06-28 18:55
Hi Molly,

thanks for this proposal.
I have to admin that I don't work with screen readers and thus things like that might gone unnoticed.

However, I don't know if I can do anything about it.

If you look at Moodle core (without our plugin, for example on https://demo.moodle.net/), you will notice that the "my courses" node is already there, but it's no link as well. This is how the Moodle core developers have built it currently. This plugin just adds the possibility to collapse the My Courses node (if you enable this feature in the plugin).

So, I can only propose two ways forward:
1. Either you will come to the conclusion that the problem is already there in Moodle core, please open an issue on https://tracker.moodle.org to discuss it with the Moodle core developers directly. Feel free to post the tracker issue URL here for reference.
2. Or you will come to the conclusion that the problem is only limited to the plugin and its collapsing feature. Then I would be happy to know this and I will try to evaluate if we can change anything about it.

Thanks,
Alex

**Comment by mepfaff** [comment] 2018-07-03 13:54
Hi Alex,

Thanks for your response; that's a fair point about the node already existing in Moodle core. I still think the issue is tied to the collapsing feature. To highlight my reasoning, here are two scenarios: 

1. Without the plugin, a user who can't use the mouse can instead use the tab key to access each node in the navigation panel. It skips over "My courses" because there's no function attached to clicking it, so no reason for it to receive tab focus. 
2. With the plugin installed and "My courses" collapsed by default, now it is necessary to click the "My courses" node to access all the hidden nodes beneath it, meaning those links can no longer be accessed by anyone who can't use a mouse. 

Instead of making it a link, is there a way to add the tabindex attribute and listen for an enter/spacebar keydown event? (This is just a guess based on my very limited web development knowledge; you may have a better idea.) That would solve 99% of the problem.

The main issue is that I'd prefer to keep "My courses" collapsed by default (since it saves room), but for now I can't use that feature because our college policy requires us to follow [WCAG 2.0](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#keyboard-accessible) Levels A - AA. (This is becoming a common standard for other institutions to follow as well, since lots of schools are getting hit with complaints/lawsuits related to web accessibility at the moment.)

Thanks so much for your time!

**Comment by abias** [comment] 2018-07-19 08:06
Hi Molly,

I think I have understood the problem now.
However, it's still a fact that the mycourses node is delivered as a div and not as a a tag by Moodle core. The mycourses node is one single node in Moodle core's nav drawer which only acts as a heading and thus is no link.

Before I dive into a solution (in my plugin or in Moodle core), I would now be curious if the other collapsible heading nodes which are added by the plugin are fine for you as they are true links:

Could you please set these settings:
* local_boostnavigation | collapsecustombottomnodesadmins = Yes
* local_boostnavigation | insertcustombottomnodesadmins = 
```
Site administration quicklinks|/admin/search.php
-List of users|/admin/user.php
-Manage courses|/course/management.php
-Notifications|/admin/index.php
```
* local_boostnavigation | insertcoursesectionscoursenode = Yes
* local_boostnavigation | collapsecoursesectionscoursenode = Yes

and check then
1. the added "sections" node within a course
2. the added "Site administration quicklinks" at the bottom of the nav drawer
if a keyboard-only user can use these nodes in your point of you?

Thanks,
Alex

**Comment by mepfaff** [comment] 2018-07-23 16:47
I did as you asked, and those two nodes (and their contents) can be accessed with Tab and activated with the Enter key. 

Thank you!

**Comment by josephfranciskumar** [comment] 2018-08-25 06:59
Hi Abis,

Where i have to do these settings in moodle?


Could you please set these settings:

local_boostnavigation | collapsecustombottomnodesadmins = Yes
local_boostnavigation | insertcustombottomnodesadmins =.

Please see the attchement. And i tried to create nodes with sub nodes. coulnt able to do that.

![capture](https://user-images.githubusercontent.com/42690983/44615903-63d58880-a862-11e8-9d68-f9718562bc70.PNG)

**Comment by josephfranciskumar** [comment] 2018-08-25 07:09
can i create menus with sub menus in this plugin?

Please support for this.

Thanks.

**Comment by abias** [comment] 2019-02-05 12:40
@josephfranciskumar ,
I am sorry but your comments above are not related to this issue. If you are having trouble with this plugin, please create a new issue.

----

@mepfaff ,
I am sorry for my really late reply. I was busy with other work and lost sight of this issue.

I have now implemented an improvement in https://github.com/moodleuulm/moodle-local_boostnavigation/commit/3bd93b71528669a1ff7f1f7bfe3aa06118a80158 which allowed a user - at least in my tests - to tab over the mycourses node even if it is configured to be collapsible and which also allowed him to open / close the node by pressing the Enter button. Additionally, I added some aria attributes to explain that the nodes are collapsible.

I would be really grateful if you could have a look at the changes by downloading the latest version from the master branch and give me some feedback if the solution works in your point of view.

Cheers,
Alex

**Comment by abias** [comment] 2019-02-06 13:10
Hi @mepfaff,

I have released a new version to the Moodle plugin repo containing the accessibility improvements today.

I dare to close this issue now as fixed.

If you see any more problems, don't hesitate to back to me.

Thanks,
Alex

**Closed as completed by abias** 2019-02-06 13:10 UTC
