### ISSUE TITLE
Custom course nodes breaking the navdrawer navigation on Moodle 3.9

### ISSUE THREAD

**Issue by izendegi** [moodleuulm/moodle-local_boostnavigation#72] opened 2020-09-09 12:38 UTC
Hi there,

We've realized that there is an issue when we add a custom course node to the navdrawer. We've tried adding this node for all users:
_Course settings|/course/edit.php?id={courseid}|||editingteacher|||fa-cogs|editcoursesettings|participants_

After doing that it works fine only for one course of the course list, but when navigating to another course two issues show up:
- The course node doesn't show up
- The same course of the list always appears as the selected one, even if there is another one showed on the screen

We're experiencing this on Moodle 3.9.1 with local_boostnavigation v3.8-r2

**Comment by abias** [comment] 2020-11-10 19:56
Hey @izendegi 

now that the 3.9 release of this plugin is finally out, I have tested the reported issue on 3.9 - and I was not able to reproduce it. The node configuration worked fine for me and the "Course settings" node appeared in all courses, linking to the correct course settings page.

Could you please test again, ideally on a fresh installation of Moodle 3.9, with the v3.9-1 release of the plugin?
If you can reproduce this issue, please provide steps to reproduce for me.

Thanks,
Alex

**Comment by izendegi** [comment] 2020-11-17 16:04
Hi @abias 

I've tried the new version of the plugin on a clean 3.10 instance and I can reproduce it, but I've realized the it only happens when the collapsecustomcoursenodesusers setting is also enabled.

These are the steps to reproduce it:
- Create at least two courses and enrol yourself on them (that would make them appear on the NavDrawer)
- Set insertcustomcoursenodesusers --> Course settings|/course/edit.php?id={courseid}|||editingteacher|||fa-cogs|editcoursesettings|participants
- Set collapsecustomcoursenodesusers --> Yes
- Navigate to the first course of the NavDrawer list and see that all shows up correctly:
![irudia](https://user-images.githubusercontent.com/5556433/99412084-a2990280-28f4-11eb-8dde-db2d4f8a64e8.png)
- Them navigate to the second course of the NavDrawer list and see how the course node doesn't show up and the highlighted course is the first one of the list:
![irudia](https://user-images.githubusercontent.com/5556433/99412176-b8a6c300-28f4-11eb-843e-9cb7ab29f764.png)

**Comment by abias** [comment] 2021-01-06 19:28
Hey @izendegi ,

thank you for clarifying the steps to reproduce. I could reproduce the problem now.

You are right, it only happens when the collapsecustomcoursenodesusers setting is also enabled.
And it happens independently of the course node complexity - it does not need a node with placeholders like you had in your example, even a simple custom node like `Foo|/bar.php` will trigger the problem.

I had to see that a single existing code line had a side effect to collapsible custom course nodes - but only to these, not to custom root nodes and not to custom bottom nodes.

This is fixed now in https://github.com/moodleuulm/moodle-local_boostnavigation/commit/8cfc30a4ce28ba1e69239057d2385cdc4867d10f and a official release containing the fix will be published soon.

Cheers,
Alex

**Closed as completed by abias** 2021-01-06 19:28 UTC

**Comment by izendegi** [comment] 2021-01-08 13:05
The fix works fine, thank you very much @abias !
