### ISSUE TITLE
Collapsible nodes do not collapse under Moodle 3.8

### ISSUE THREAD

**Issue by pennedav** [moodleuulm/moodle-local_boostnavigation#49] opened 2019-11-01 14:16 UTC
During my testing of Moodle 3.8 in preparation for the upcoming release I noticed that collapsible nodes do not collapse. This is with plugin version **2019082700** (release 3.7-r3) under Moodle 3.8dev+ (Build: 20191031) (version 2019103100.00). Given that we're past the Moodle code freeze for 3.8 I doubt this is a bug that will be resolved between now and the official release of 3.8 in a week or so. The problem does not appear on Moodle 3.7.1+ (Build: 20190712) (version 2019052001.01). I've included two screenshots of the Chrome developer tools: one from 3.7 and one from 3.8.

The issue appears to be that under 3.8 the navigation now encloses the `<a>` tags in an `<li>` tag so the styles that should be hiding the child items is not getting applied. See screenshots. Note the orange arrows in the 3.8 screenshot and note that proper styling is not being applied as indicated in the style area of the Chrome tools.

Moodle 3.7 screenshot:
<img width="1675" alt="Moodle 3 7" src="https://user-images.githubusercontent.com/1786996/68030538-1b003780-fc90-11e9-80d0-a5c9c5742fe4.png">

Moodle 3.8 screenshot:
<img width="1672" alt="Screen Shot 2019-11-01 at 10 33 19 AM" src="https://user-images.githubusercontent.com/1786996/68032075-47698300-fc93-11e9-8410-b23914ef57a1.png">

Edit: Updated 3.8 screenshot so it actually shows the proper state when the item should be collapsed but is not. Previous screenshot had data-hidden="0", updated has data-hidden="1" but item is not hidden.

**Comment by pennedav** [comment] 2019-12-02 16:59
This is still an issue after upgrading to the official 3.8 release.

**Comment by abias** [comment] 2019-12-04 19:22
Hi @pennedav ,

thank you for raising this issue.

This issue seems to be caused by the change of the HTML structure in Boost's navigation drawer in https://tracker.moodle.org/browse/MDL-65406. We will try this within out 3.8 release, but this will take some more days to be finished as our internal release cycle is multiple months behind the Moodle core cycle and some other things still have higher priority at the moment. 

If you can provide a pull request with a solution, this would be warmly welcome.

Thanks,
Alex

**Comment by pennedav** [comment] 2019-12-05 20:59
@abias I've created a pull request for a small change that seems to fix the issue for me. I would expect there are some cases where my patch will have negative consequences for others (removal of the tilde comparators in styles.css). I have not rigorously tested these changes. :-)

**Comment by rlorenzo** [comment] 2020-01-03 00:30
Just wanted to chip in that I tried this patch on our Moodle 3.8 instance and seems to work fine for us.

**Comment by gushagelberg2** [comment] 2020-01-23 08:02
I also tried the above fix in styles.css seems to work well on my Moodle 3.8.
Any news @pennedav when you guys will update the plugin? 
I really need your cool plugin. Seems like moodle should add these features to the Core.

**Comment by neilstapleton** [comment] 2020-02-07 14:24
> I also tried the above fix in styles.css seems to work well on my Moodle 3.8.
> Any news @pennedav when you guys will update the plugin?
> I really need your cool plugin. Seems like moodle should add these features to the Core.

Great that there is a patch that works out there, itching to see what your official 3.8 release will hold.  Any idea on a release date would be very much appropriated.

We have a code freeze for our upgrade to 3.8 on 3rd March, so our clock is ticking really. Although v3.7-r4 + patch will get us there.

**Comment by abias** [comment] 2020-02-07 17:09
Hi all,

I am sorry for the long period of silence on this issue from my side. As you know, this is a plugin which is published to the community on a volunteer basis and, once again, local requirements for other projects outplayed a quick fix of this issue for the community.

I can confirm that #50 is a working hotfix for the collapsing problem and everyone updating to 3.8 now should try it. But I have also seen that it does only fix particular symptoms instead of the root of the problem.

I have just published a last 3.7 version and am now working on finding a real solution for this issue here. This could also bring solutions to #36 and #48, but I can't promise anything at the moment.

I will keep you updated.

Cheers,
Alex

**Comment by abias** [comment] 2020-06-22 19:29
Well, I wrote the last post in this issue at the beginning of february. And then Covid-19 came around the corner and changed priorities quite fundamentally.

I am happy to report today that this issue has finally been resolved in https://github.com/moodleuulm/moodle-local_boostnavigation/commit/f3868412c0e65b63d419882b66b45b10cebfa46b.
An official 3.8 version of this plugin will be pushed within the next few days to the Moodle plugins repo as well.

Thank you all for your patience throughout these times.

Cheers,
Alex

**Closed as completed by abias** 2020-06-22 19:29 UTC
